#!/usr/bin/env sh
DBNAME=$(docker exec ws_db psql -At -U postgres -c "select coalesce(datname, 'postgres') from pg_database where datname in ('sql_workshop', 'postgres') order by datname desc;" | head -1)
docker exec -it ws_db psql -e -d $DBNAME -U postgres
exit $?

