version: '3'

services:
  ws-db:
    container_name: ws_db
    image: postgres:12
    environment:
    - POSTGRES_DB=${DATABASE_NAME-postgres}
    - POSTGRES_USER=${DATABASE_USER-postgres}
    - POSTGRES_PASSWORD=${DATABASE_PASSWORD-postgres}
    ports:
      - "15444:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    command:
      # This command give more precise control over the parameter settings
      # Included are loading the pg_stat_statements lib
      # as well as autovacuum settings that are designed to make more efficient
      # use of the autovacuum processes
      # The pg_init mount is still needed to enable the necesary extensions.
      - postgres
      - -c
      - max_connections=1710
      - -c
      - shared_preload_libraries=pg_stat_statements
      - -c
      - autovacuum_max_workers=8
      - -c
      - autovacuum_vacuum_cost_limit=4800
      - -c
      - autovacuum_vacuum_cost_delay=10
      - -c
      - idle_in_transaction_session_timeout=30000
      - -c
      - pg_stat_statements.max=2000
      - -c
      - pg_stat_statements.save=off
      - -c
      - pg_stat_statements.track_utility=off
      - -c
      - track_activity_query_size=2048
      - -c
      - log_min_error_statement=error
      - -c
      - log_min_duration_statement=2000
      - -c
      - track_functions=pl

  ws-pgadmin:
    container_name: ws_pgAdmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL-postgres}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD-postgres}
    ports:
      - "${PGADMIN_PORT-8432}:80"
    volumes:
      - ./pgadmin_servers.json:/pgadmin4/servers.json
    links:
      - ws-db

  ws-grafana:
    container_name: ws_grafana
    build:
        context: grafana
        dockerfile: Dockerfile-grafana
    ports:
        - 3002:3000
    links:
        - ws-db
    depends_on:
        - ws-db
